#!/bin/sh

curl -s 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' | base64 -D | grep --color=none -vE '^(!|@@|/|%|\[)' | grep -oE '[a-z0-9]([a-z0-9_\.\-]*[a-z0-9])?\.[a-z]{2,6}' | sort -u | awk '{printf("ipset=/%s/gfw\nserver=/%s/8.8.8.8\n",$0,$0)}' > etc/dnsmasq.d/gfw.conf && echo 'ipset=/google.com/gfw\nserver=/google.com/8.8.8.8\nipset=/google.cn/gfw\nserver=/google.cn/8.8.8.8' >> etc/dnsmasq.d/gfw.conf
