#!/bin/sh

curl -s 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt' | base64 -d | grep -vE '^(!|@@|/|%|\[)' | grep -oE '[a-z0-9]([a-z0-9_\.\-]*[a-z0-9])?\.[a-z]{2,6}' | sort -u | awk '{printf("ipset=/%s/setmefree\nserver=/%s/8.8.8.8\n",$0,$0)}' > gfw.conf && echo -e "ipset=/google.com/setmefree\nserver=/google.com/8.8.8.8\nipset=/google.cn/setmefree\nserver=/google.cn/8.8.8.8" >> gfw.conf
