#!/bin/sh

echo `curl http://www.ishadowsocks.net/` > .t 
pass=`sed 's/.*A密码:\([0-9]\{8\}\).*/\1/' .t`
echo "New password for US: ${pass}"
sed -i "s/\"password\":\"[0-9]\{8\}\"/\"password\":\"${pass}\"/" us-config.json

pass=`sed 's/.*B密码:\([0-9]\{8\}\).*/\1/' .t`
echo "New password for HK: ${pass}"
sed -i "s/\"password\":\"[0-9]\{8\}\"/\"password\":\"${pass}\"/" hk-config.json

pass=`sed 's/.*C密码:\([0-9]\{8\}\).*/\1/' .t`
echo "New password for JP: ${pass}"
sed -i "s/\"password\":\"[0-9]\{8\}\"/\"password\":\"${pass}\"/" jp-config.json
